// <auto-generated />
namespace SmartReward.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class seennotification : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(seennotification));
        
        string IMigrationMetadata.Id
        {
            get { return "201409151145056_seen-notification"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
