// <auto-generated />
namespace SmartReward.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class notification_response : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(notification_response));
        
        string IMigrationMetadata.Id
        {
            get { return "201409081318264_notification_response"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
